/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.38
 * Generated at: 2019-04-15 05:43:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.naver;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reversegocoder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1552270070766L));
    _jspx_dependants.put("jar:file:/C:/Users/student/web-server/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/tour/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=rbeyz68rf5&submodules=geocoder\">\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tif (navigator.geolocation) {\r\n");
      out.write("\t\t\tnavigator.geolocation.getCurrentPosition(onSuccessGeolocation, // 위치 정보 얻기 성공 시 핸들러 \r\n");
      out.write("\t\t\tonErrorGeolocation); // 위치 정보 얻기 실패 시 핸들러 \r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tnaver.maps.Service.reverseGeocode({\r\n");
      out.write("\t\t\tlocation : new naver.maps.LatLng(37.3595316, 127.1052133),\r\n");
      out.write("\t\t}, function(status, response) {\r\n");
      out.write("\t\t\tif (status !== naver.maps.Service.Status.OK) {\r\n");
      out.write("\t\t\t\treturn alert('Something wrong!');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar result = response.result, // 검색 결과의 컨테이너\r\n");
      out.write("\t\t\titems = result.items; // 검색 결과의 배열\r\n");
      out.write("\t\t\tconsole.log(items)\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tfunction onSuccessGeolocation(position) {\r\n");
      out.write("\t\t\tvar location = new naver.maps.LatLng(position.coords.latitude,\r\n");
      out.write("\t\t\t\t\tposition.coords.longitude);\r\n");
      out.write("\t\t\tmap.setCenter(location); // 얻은 좌표를 지도의 중심으로 설정합니다. \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar marker = new Maker({\r\n");
      out.write("\t\t\t\tposition : location,\r\n");
      out.write("\t\t\t\tmap : map\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tmap.setCenter(location);\r\n");
      out.write("\t\t\tmap.setZoom(12);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction onErrorGeolocation() {\r\n");
      out.write("\t\t\tvar center = map.getCenter();\r\n");
      out.write("\t\t\tinfowindow\r\n");
      out.write("\t\t\t\t\t.setContent('<div style=\"padding:20px;\">'\r\n");
      out.write("\t\t\t\t\t\t\t+ '<h5 style=\"margin-bottom:5px;color:#f00;\">Geolocation failed!</h5>'\r\n");
      out.write("\t\t\t\t\t\t\t+ \"latitude: \" + center.lat() + \"<br />longitude: \"\r\n");
      out.write("\t\t\t\t\t\t\t+ center.lng() + '</div>');\r\n");
      out.write("\t\t\tinfowindow.open(map, center);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
